module.exports = function(grunt) {
    grunt.loadNpmTasks('grunt-screeps');
    grunt.loadNpmTasks('grunt-contrib-jshint');

    grunt.initConfig({
        creds: grunt.file.readJSON('config/screeps-creds.json'),
        screeps: {
            options: {
                email: '<%= creds.email %>',
                password: '<%= creds.password %>',
                branch: grunt.option('branch') || 'default',
                ptr: false
            },
            dist: {
                src: ['*.js']
            }
        },
          jshint: {
            all: ['*.js'],
            options: {
                esversion: 6,
                loopfunc: true,
                globals: {
                    "_": false,
                    exports: true,
                    Memory: true,
                    Game: true,
                    "Game.map": true,
                    "Game.market": true,
                    PathFinder: true,
                    RawMemory: true,
                    ConstructionSite: true,
                    Creep: true,
                    Flag: true,
                    Mineral: true,
                    Nuke: true,
                    OwnedStructure: true,
                    "PathFinder.CostMatrix": true,
                    Resource: true,
                    Room: true,
                    RoomObject: true,
                    RoomPosition: true,
                    RoomVisual: true,
                    Source: true,
                    Structure: true,
                    StructureContainer: true,
                    StructureController: true,
                    StructureExtension: true,
                    StructureExtractor: true,
                    StructureKeeperLair: true,
                    StructureLab: true,
                    StructureLink: true,
                    StructureNuker: true,
                    StructureObserver: true,
                    StructurePowerBank: true,
                    StructurePowerSpawn: true,
                    StructurePortal: true,
                    StructureRampart: true,
                    StructureRoad: true,
                    StructureSpawn: true,
                    StructureStorage: true,
                    StructureTerminal: true,
                    StructureTower: true,
                    StructureWall: true,
                    OK: true,
                    ERR_NOT_OWNER: true,
                    ERR_NO_PATH: true,
                    ERR_NAME_EXISTS: true,
                    ERR_BUSY: true,
                    ERR_NOT_FOUND: true,
                    ERR_NOT_ENOUGH_ENERGY: true,
                    ERR_NOT_ENOUGH_RESOURCES: true,
                    ERR_INVALID_TARGET: true,
                    ERR_FULL: true,
                    ERR_NOT_IN_RANGE: true,
                    ERR_INVALID_ARGS: true,
                    ERR_TIRED: true,
                    ERR_NO_BODYPART: true,
                    ERR_NOT_ENOUGH_EXTENSIONS: true,
                    ERR_RCL_NOT_ENOUGH: true,
                    ERR_GCL_NOT_ENOUGH: true,
                    STRUCTURE_SPAWN: true,
                    STRUCTURE_EXTENSION: true,
                    STRUCTURE_ROAD: true,
                    STRUCTURE_WALL: true,
                    STRUCTURE_RAMPART: true,
                    STRUCTURE_KEEPER_LAIR: true,
                    STRUCTURE_PORTAL: true,
                    STRUCTURE_CONTROLLER: true,
                    STRUCTURE_LINK: true,
                    STRUCTURE_STORAGE: true,
                    STRUCTURE_TOWER: true,
                    STRUCTURE_OBSERVER: true,
                    STRUCTURE_POWER_BANK: true,
                    STRUCTURE_POWER_SPAWN: true,
                    STRUCTURE_EXTRACTOR: true,
                    STRUCTURE_LAB: true,
                    STRUCTURE_TERMINAL: true,
                    STRUCTURE_CONTAINER: true,
                    STRUCTURE_NUKER: true,
                    FIND_EXIT_TOP: true,
                    FIND_EXIT_RIGHT: true,
                    FIND_EXIT_BOTTOM: true,
                    FIND_EXIT_LEFT: true,
                    FIND_EXIT: true,
                    FIND_CREEPS: true,
                    FIND_MY_CREEPS: true,
                    FIND_HOSTILE_CREEPS: true,
                    FIND_SOURCES_ACTIVE: true,
                    FIND_SOURCES: true,
                    FIND_DROPPED_ENERGY: true,
                    FIND_DROPPED_RESOURCES: true,
                    FIND_STRUCTURES: true,
                    FIND_MY_STRUCTURES: true,
                    FIND_HOSTILE_STRUCTURES: true,
                    FIND_FLAGS: true,
                    FIND_CONSTRUCTION_SITES: true,
                    FIND_MY_SPAWNS: true,
                    FIND_HOSTILE_SPAWNS: true,
                    FIND_MY_CONSTRUCTION_SITES: true,
                    FIND_HOSTILE_CONSTRUCTION_SITES: true,
                    FIND_MINERALS: true,
                    FIND_NUKES: true,
                }
            }
        }
    });
  grunt.task.registerTask('default', ['jshint']);
  grunt.task.registerTask('deploy', ['jshint', 'screeps']);
};